### ISSUE TITLE
ViaProxy cannot find Resource "Swarm" in newest azalea version, according to bevy_ecs

### ISSUE THREAD

**Issue by EnderKill98** [azalea-rs/azalea-viaversion#7]
I have no idea how to solve this rn. It seems to build, but then doesn't run.

Might or might not be an actual issue.

![grafik](https://github.com/azalea-rs/azalea-viaversion/assets/117233381/cdc93507-d1b4-4551-9e3b-caebc7907a29)

**Comment by ShayBox** [comment]
You're using a fork of Azalea, but this plugin isn't using the same fork, see #9  
You have to use cargo patch to swap it out in the entire dependency tree
